# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg2-githubactions with AZ CLI
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: cf356559-447f-4ef5-a596-5843ea2a66de
          region: East US
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg2-githubactions
       